# Generated by Django 4.1.3 on 2024-06-24 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snip', '0002_book_delete_snippet'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=255)),
                ('subcategory', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('amount', models.PositiveIntegerField()),
            ],
        ),
    ]
