# Generated by Django 4.1.3 on 2024-06-25 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snip', '0004_remove_item_amount_remove_item_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='price',
            field=models.IntegerField(default=1),
        ),
    ]
