# Generated by Django 4.1.3 on 2024-06-25 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snip', '0005_alter_item_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='price',
            field=models.DecimalField(decimal_places=2, default=1.2, max_digits=10),
        ),
    ]
